const colors = {
  light: {
    text: "#0f0f14",
    tint: "#4B9EFF",
    background: "#F2F2F7",
    foreground: "#0f0f14",
    card: "#FFFFFF",
    cardForeground: "#0f0f14",
    primary: "#4B9EFF",
    primaryForeground: "#FFFFFF",
    secondary: "#E8E8F0",
    secondaryForeground: "#1a1a2e",
    muted: "#E8E8F0",
    mutedForeground: "#8A8A9A",
    accent: "#2EC4A7",
    accentForeground: "#FFFFFF",
    destructive: "#F04848",
    destructiveForeground: "#FFFFFF",
    border: "#DCDCE8",
    input: "#DCDCE8",
    success: "#2EC4A7",
    warning: "#F5A623",
    spendingCard: "#1A2D58",
  },
  dark: {
    text: "#F0F0F8",
    tint: "#4B9EFF",
    background: "#0B0B14",
    foreground: "#F0F0F8",
    card: "#141421",
    cardForeground: "#F0F0F8",
    primary: "#4B9EFF",
    primaryForeground: "#FFFFFF",
    secondary: "#1A1A2A",
    secondaryForeground: "#E0E0F0",
    muted: "#1A1A2A",
    mutedForeground: "#707088",
    accent: "#2EC4A7",
    accentForeground: "#FFFFFF",
    destructive: "#F04848",
    destructiveForeground: "#FFFFFF",
    border: "#1E1E32",
    input: "#1E1E32",
    success: "#2EC4A7",
    warning: "#F5A623",
    spendingCard: "#0F1E40",
  },
  radius: 14,
};

export default colors;
